apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tas-tpa-int
  janus-idp.io/tekton: tas-tpa-int
  backstage.io/kubernetes-id: tas-tpa-int
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tas-tpa-int
resources: 
- deployment.yaml
- route.yaml
- service.yaml
