apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: tas-tpa-int
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tas-tpa-int 
  name: tas-tpa-int
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tas-tpa-int
    weight: 100 
