apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tas-tpa-int
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tas-tpa-int 
  name: tas-tpa-int
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tas-tpa-int 
